create database customer_behavior;
use customer_behavior;
select * from customer;
-- How many unique customers belong to each age group, and what is the total sales generated by each group?
select age_group,count(distinct customer_id) as total_customer,sum(total_amount) as total_sales from customer group by age_group;
-- Which are the top 10 customers based on total revenue generated?
select customer_id,sum(total_amount) as total_revenue from customer group by customer_id order by total_revenue desc limit 10;
-- Which customers have made more than one purchase?
select customer_id,count(transaction_id) as purchase_count from customer group by customer_id having purchase_count > 1;
-- What is the total sales amount for each month?
select date_format(date,'%Y-%m') as month, sum(total_amount) as total_sales from customer group by month order by month; 
-- Which product category generates the highest total sales?
select product_category,sum(total_amount) as total_sales from customer group by product_category order by total_sales desc;
-- What is the total lifetime spending of each customer?
select customer_id,sum(total_amount) as lifetime_amount from customer group by customer_id;
-- Which customers have total spending higher than the overall average spending?
select customer_id,sum(total_amount) as total_spent from customer group by customer_id having total_spent > (select avg(total_amount) from customer);
-- What are the total and average sales for each gender?
select gender,sum(total_amount) as total_sales,round(avg(total_amount),2) as avg_sales from customer group by gender;
-- What is the total sales generated in each quarter?
select quarters, sum(total_amount) as total_sales from customer group by quarters order by quarters; 
-- Which customers have not made any purchase in the last six months?
select customer_id,max(date) as last_date from customer group by customer_id having max(date) < date_sub(curdate(),interval 6 month);
